db:
  container_name: "database"
  image: mysql:latest
  environment:
    MYSQL_DATABASE: testeDB
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
app:
  build: .
  volumes:
    - .:/javaee-wildfly-mysql
  command: sh /opt/jboss/wildfly/customization/execute.sh
  ports:
    - '8080:8080'
    - '9990:9990'
  links:
   - db
  environment:
    - MYSQL_URI=db:3306
